<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { FeatherSpinner } from '@featherds/progress'
import { FeatherButton } from '@featherds/button'
import { getClaudeSuggestion } from '@/services/AlecService'
import { TClaudeSuggestion } from '@/types/TUser'

const props = defineProps<{
	situationId: number | string
}>()

// Server states: pending (Claude call in flight), ready (suggestions
// available), failed (last attempt errored). Plus three UI-only states:
//   absent  — server returned 204; feature is off or call hasn't fired
//   loading — initial fetch in progress
//   error   — the GET itself failed (network / 500)
type UiState = 'loading' | 'absent' | 'pending' | 'ready' | 'failed' | 'error'

const state = ref<UiState>('loading')
const record = ref<TClaudeSuggestion | null>(null)

// Poll cadence and cap. We pick 5s because Claude calls with prompt caching
// usually complete in 5–30s, and 5 minutes is a generous ceiling — anything
// longer is almost certainly a server-side timeout that we'll see as 'failed'.
const POLL_INTERVAL_MS = 5_000
const POLL_TIMEOUT_MS = 5 * 60 * 1_000

let pollHandle: ReturnType<typeof setInterval> | null = null
let pollStartedAt = 0

const stopPolling = () => {
	if (pollHandle !== null) {
		clearInterval(pollHandle)
		pollHandle = null
	}
}

const startPollingIfPending = () => {
	if (state.value !== 'pending') return
	if (pollHandle !== null) return
	pollStartedAt = Date.now()
	pollHandle = setInterval(async () => {
		if (Date.now() - pollStartedAt > POLL_TIMEOUT_MS) {
			// We've polled for 5 min without a terminal state. Stop and let the
			// user trigger a manual refresh — better than burning HTTP forever.
			stopPolling()
			return
		}
		await fetchOnce()
		if (state.value !== 'pending') {
			stopPolling()
		}
	}, POLL_INTERVAL_MS)
}

const fetchOnce = async () => {
	const result = await getClaudeSuggestion(props.situationId)
	if (result === false) {
		state.value = 'error'
		return
	}
	if (result === null) {
		state.value = 'absent'
		record.value = null
		return
	}
	record.value = result
	state.value = result.status as UiState
}

const handleRefresh = async () => {
	state.value = 'loading'
	stopPolling()
	await fetchOnce()
	startPollingIfPending()
}

onMounted(async () => {
	await fetchOnce()
	startPollingIfPending()
})

onBeforeUnmount(() => stopPolling())

const requestedAtFormatted = computed(() => {
	if (!record.value?.requestedAt) return ''
	return new Date(record.value.requestedAt).toLocaleString()
})
</script>

<template>
	<div class="ai-panel" data-test="ai-suggestions-panel">
		<div class="header">
			<h3>AI Suggestions</h3>
			<FeatherButton
				secondary
				data-test="ai-refresh"
				@click="handleRefresh"
			>
				Refresh
			</FeatherButton>
		</div>

		<div v-if="state === 'loading'" class="state-row" data-test="ai-loading">
			<FeatherSpinner />
			<span>Loading…</span>
		</div>

		<div v-else-if="state === 'absent'" class="state-row" data-test="ai-absent">
			No AI suggestions are available for this situation. The Claude
			integration may be disabled, or the analysis has not run yet — check
			the
			<router-link to="/account">account settings</router-link> to enable it.
		</div>

		<div v-else-if="state === 'pending'" class="state-row" data-test="ai-pending">
			<FeatherSpinner />
			<span>
				Analyzing alarms with Claude… requested at
				{{ requestedAtFormatted }}.
			</span>
		</div>

		<div
			v-else-if="state === 'failed'"
			class="state-row failed"
			data-test="ai-failed"
		>
			<div class="failed-msg">
				The last Claude request failed:
				<code>{{ record?.error || 'unknown error' }}</code>
			</div>
			<FeatherButton
				secondary
				data-test="ai-retry"
				@click="handleRefresh"
			>
				Retry
			</FeatherButton>
		</div>

		<div v-else-if="state === 'error'" class="state-row" data-test="ai-error">
			Could not load suggestions. Please retry.
			<FeatherButton secondary @click="handleRefresh">Retry</FeatherButton>
		</div>

		<div v-else-if="state === 'ready' && record" data-test="ai-ready">
			<div class="meta" v-if="record.completedAt">
				Generated by <strong>{{ record.model }}</strong> at
				{{ new Date(record.completedAt).toLocaleString() }}. Treat as
				hypotheses, not facts.
			</div>

			<div class="section">
				<h4>Probable root causes</h4>
				<ol
					v-if="record.rootCauses.length"
					data-test="ai-root-causes"
				>
					<li
						v-for="(cause, idx) in record.rootCauses"
						:key="`cause-${idx}`"
					>
						{{ cause }}
					</li>
				</ol>
				<div v-else class="empty">No root causes returned.</div>
			</div>

			<div class="section">
				<h4>Possible resolutions</h4>
				<ol
					v-if="record.resolutions.length"
					data-test="ai-resolutions"
				>
					<li
						v-for="(res, idx) in record.resolutions"
						:key="`res-${idx}`"
					>
						{{ res }}
					</li>
				</ol>
				<div v-else class="empty">No resolutions returned.</div>
			</div>
		</div>
	</div>
</template>

<style lang="scss" scoped>
@use '@/styles/variables.scss';

.ai-panel {
	background-color: #ffffff;
	border: 1px solid variables.$border-grey;
	padding: 20px;
	margin-top: 10px;
}

.header {
	display: flex;
	align-items: center;
	justify-content: space-between;
	margin-bottom: 14px;

	h3 {
		margin: 0;
		font-size: 18px;
	}
}

.state-row {
	display: flex;
	align-items: center;
	gap: 12px;
	color: #555;
	font-size: 14px;

	&.failed {
		justify-content: space-between;
		color: #963;
	}

	.failed-msg {
		flex: 1;
		margin-right: 12px;
	}

	code {
		background: #f5f0e6;
		padding: 1px 5px;
		border-radius: 2px;
		font-size: 12px;
	}
}

.meta {
	font-size: 13px;
	color: #666;
	margin-bottom: 12px;
}

.section {
	margin-top: 16px;

	h4 {
		font-size: 15px;
		margin: 0 0 8px;
	}

	ol {
		margin: 0;
		padding-left: 22px;

		li + li {
			margin-top: 6px;
		}
	}
}

.empty {
	font-style: italic;
	color: #888;
	font-size: 13px;
}
</style>
