
:imagesdir: ../assets/images
= Pre-Installation Tasks
:description: View pre-installation tasks for OpenNMS's Architecture for Learning Enabled Correlation (ALEC): configuration, enable alarm history storage and syslogd, etc.

This section describes the configuration tasks that you must complete before installing ALEC.

== OpenNMS configuration

Before you install ALEC, you must configure your OpenNMS instance.

=== Set \$OPENNMS_HOME variable

The ALEC installation documentation refers to the `$OPENNMS_HOME` environment variable, which does not exist by default.
To create it, use the command that is appropriate for your Linux distribution:

* *RHEL/CentOS:* `export OPENNMS_HOME=/opt/opennms`
* *Ubuntu/Debian:* `export OPENNMS_HOME=/usr/share/opennms`

=== Verify OpenNMS installation

Run `opennms:health-check` in an OpenNMS Karaf shell to verify the status of your Horizon or Meridian instance.
If the command returns `Everything is awesome`, continue with the next task.
If it returns `Oh no, something is wrong`, you must address the underlying problem before continuing.

=== Enable syslogd

We recommend that you enable https://docs.opennms.com/horizon/latest/reference/daemons/daemon-config-files/syslogd.html[syslogd] to take advantage of the syslog patterns and event definitions that ALEC provides.

Edit `$OPENNMS_HOME/etc/service-configuration.xml` and change the following code:

[source, xml]
----
<service enabled="false">
    <name>OpenNMS:Name=Syslogd</name>
----

to:

[source, xml]
----
<service>
    <name>OpenNMS:Name=Syslogd</name>
----

This change occurs the next time OpenNMS restarts.

WARNING: Do not restart OpenNMS at this point; you will restart it as part of the ALEC installation process.

== Set up package repositories

Packages for ALEC are available in the same `yum` and `apt` repositories as OpenNMS, and as downloads on the https://github.com/OpenNMS-Plugins/alec/releases[ALEC releases page].
If you already have the stable repository installed, you can skip this step.

Install the repository using the commands that are appropriate for your system:

* *RHEL/CentOS:*
+
[source, shell]
----
yum -y install https://yum.opennms.org/repofiles/opennms-repo-stable-rhel7.noarch.rpm
rpm --import https://yum.opennms.org/OPENNMS-GPG-KEY
----

* *Ubuntu/Debian:*
+
[source, shell]
----
cat << EOF | sudo tee /etc/apt/sources.list.d/opennms.list
deb https://debian.opennms.org stable main
deb-src https://debian.opennms.org stable main
EOF
wget -O- https://debian.opennms.org/OPENNMS-GPG-KEY | tee -a /etc/apt/trusted.gpg.d/opennms.asc
----
